# Generated by Django 6.0.3 on 2026-04-01 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('power', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=100)),
                ('category', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PkmStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('def_esp', models.IntegerField(blank=True, null=True)),
                ('def_fis', models.IntegerField(blank=True, null=True)),
                ('att_esp', models.IntegerField(blank=True, null=True)),
                ('att_fis', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('ev_limit', models.IntegerField(default=508)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('encrypted_pass', models.CharField(max_length=300)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sound', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('front_sprite', models.URLField(blank=True, null=True)),
                ('lvl', models.IntegerField(default=1)),
                ('first_type', models.CharField(max_length=150)),
                ('second_type', models.CharField(blank=True, max_length=150, null=True)),
                ('pkm_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.pkmstats')),
            ],
        ),
        migrations.CreateModel(
            name='PkmMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.moves')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('in_progress', 'En progreso'), ('finished', 'Finalizada')], default='waiting', max_length=20)),
                ('battle_type', models.CharField(choices=[('normal', 'Normal'), ('random', 'Aleatoria')], default='normal', max_length=20)),
                ('user_team', models.JSONField(default=dict)),
                ('opponent_team', models.JSONField(default=dict)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_received', to='rest_api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_started', to='rest_api.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='rest_api.user')),
            ],
        ),
    ]
