# Generated by Django 6.0.3 on 2026-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_sesion',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
