# Generated by Django 6.0.3 on 2026-04-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_user_token_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmstats',
            name='ev_limit',
        ),
    ]
