# Generated by Django 6.0.3 on 2026-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_remove_pkmstats_ev_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='back_sprite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
