# Generated by Django 6.0.3 on 2026-04-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_pokemon_back_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sound',
            field=models.URLField(blank=True, null=True),
        ),
    ]
