# Generated by Django 6.0.1 on 2026-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_pokemon_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='back_sprite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_sesion',
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_limit',
            field=models.IntegerField(default=508),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
    ]
