# Generated by Django 6.0.1 on 2026-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_pokemon_back_sprite_remove_user_token_sesion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmstats',
            name='ev_limit',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='back_sprite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_sesion',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sound',
            field=models.URLField(blank=True, null=True),
        ),
    ]
