# Generated by Django 6.0.1 on 2026-04-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_remove_pkmstats_ev_limit_pokemon_back_sprite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='battle_type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slot',
        ),
        migrations.AddField(
            model_name='moves',
            name='desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='effect_chance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moves',
            name='effect_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moves',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moves',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moves',
            name='category',
            field=models.CharField(choices=[('physical', 'Físico'), ('special', 'Especial'), ('status', 'Estado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moves',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='moves',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moves',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_sesion',
            field=models.CharField(default=150),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='TurnBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField()),
                ('user_act', models.CharField(choices=[('attack', 'Attack'), ('change_pkm', 'Change Pokemon'), ('not_selected', 'Not selected')], default='not_selected', max_length=20)),
                ('opponent_act', models.CharField(choices=[('attack', 'Attack'), ('change_pkm', 'Change Pokemon'), ('not_selected', 'Not selected')], default='not_selected', max_length=20)),
                ('user_act_value', models.CharField(blank=True, max_length=50, null=True)),
                ('opp_act_value', models.CharField(blank=True, max_length=50, null=True)),
                ('resolve', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.battle')),
            ],
        ),
    ]
