# Generated by Django 6.0.5 on 2026-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_remove_battle_battle_type_remove_team_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='stat_change_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnbattle',
            name='turn_log',
            field=models.JSONField(default=list),
        ),
    ]
