# Generated by Django 6.0.5 on 2026-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_moves_stat_change_amount_turnbattle_turn_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='status_count',
            field=models.IntegerField(default=0),
        ),
    ]
