# Generated by Django 6.0.5 on 2026-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_pokemon_status_pokemon_status_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(default='hardy', max_length=20),
        ),
    ]
