# Generated by Django 6.0.5 on 2026-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_pokemon_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmstats',
            name='ev_att',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_att_esp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_def_esp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pkmstats',
            name='ev_speed',
            field=models.IntegerField(default=0),
        ),
    ]
